language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib install 986 # LSM303

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=micro
- BOARD=megaatmega2560
- BOARD=yun

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
